platform :ios, '10.0'

target 'CodeForces' do
  use_frameworks!

  pod 'SwiftGen', '~> 5.3'
  pod 'Reusable', '~> 4.0'
  pod 'Moya', '~> 11.0'
  pod 'RealmSwift', '~> 3.7.5'
  pod 'TagListView', '~> 1.0'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'Sourcery'

    target 'CodeForcesTests' do
      inherit! :search_paths
    end

end
